[package]
name = "smart-ups"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "*"
ssh2 = "*"
log = "*"
env_logger = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_12"] }
